---
- name: download confd
  get_url: "url={{confd_download}} dest={{confd_home}}/confd"

- name: change confd permissions
  file: "path={{confd_home}}/confd mode=0755"
  
- name: Create confd directory
  file: "state=directory path={{confd_config}}"

- name: Create confd conf.d directory
  file: "state=directory path={{confd_config}}/conf.d"

- name: Create confd templates directory
  file: "state=directory path={{confd_config}}/templates"
